#!/usr/bin/env python3
# NOTICE: Generated by an LLM-based coding system. Review/edit/test before relying on it.
"""Insert a 'compiled' timestamp note into a deck's Sources slide.

Edits the given Markdown/Quarto deck in place. The build script calls this on a
throwaway copy of each deck immediately before `quarto render`, so the rendered
HTML/PDF carries the moment it was compiled. The note reads, e.g.:

    Last modified and compiled June 17, 17:00h.

Placement, in order of preference, inside the slide whose header carries the
`.sources` class:
  1. right after the `GitHub source:` bullet (the markdown-source link), or
  2. right after the `... built with Quarto ...` line, or
  3. after the last list item in the slide, or
  4. as a plain line before the slide ends.

The timestamp is generated here (not in the shell) so day/time formatting is
portable across BSD/GNU. Idempotent: re-running on an already-stamped file is a
no-op. Usage: python3 stamp_source_note.py <deck.md>
"""
import re
import sys
from datetime import datetime

NOTE_PREFIX = "Last modified and compiled "


def marker_of(line):
    """Return (indent, marker, spacing) for a list item, or None.

    For ordered items the marker is normalized to '1.'/'1)' because Pandoc
    renumbers ordered lists by position, so the written number is irrelevant.
    """
    m = re.match(r"^(\s*)([0-9]+[.)]|[-*+])(\s+)", line)
    if not m:
        return None
    indent, mk, sp = m.group(1), m.group(2), m.group(3)
    if mk[-1] in ".)":
        mk = "1" + mk[-1]
    return indent, mk, sp


def main():
    path = sys.argv[1]
    dt = datetime.now()
    timestamp = f"{dt:%B} {dt.day}, {dt:%H:%M}h"
    note = f"{NOTE_PREFIX}{timestamp}."

    text = open(path, encoding="utf-8").read()
    if NOTE_PREFIX in text:
        return  # already stamped
    lines = text.split("\n")

    # Find the Sources slide: a header line carrying the `.sources` class.
    start = None
    for i, line in enumerate(lines):
        if line.lstrip().startswith("#") and ".sources" in line:
            start = i
            break
    if start is None:
        return  # no Sources slide; nothing to do

    # The slide ends at the next standalone `---` separator (or EOF).
    end = len(lines)
    for i in range(start + 1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    block = range(start + 1, end)

    def insert_after(idx, mk):
        indent, marker, sp = mk
        lines.insert(idx + 1, f"{indent}{marker}{sp}{note}")

    # 1) After the markdown-source bullet.
    for i in block:
        if "GitHub source:" in lines[i] and marker_of(lines[i]):
            insert_after(i, marker_of(lines[i]))
            break
    else:
        # 2) After the "built with Quarto" line.
        for i in block:
            if "Quarto" in lines[i] and "built" in lines[i].lower():
                insert_after(i, marker_of(lines[i]) or ("", "1.", " "))
                break
        else:
            # 3) After the last list item in the slide.
            last = max((i for i in block if marker_of(lines[i])), default=None)
            if last is not None:
                insert_after(last, marker_of(lines[last]))
            else:
                # 4) Nothing list-like; drop a plain line before the slide ends.
                lines.insert(end, note)

    open(path, "w", encoding="utf-8").write("\n".join(lines))


if __name__ == "__main__":
    main()
