#!/usr/bin/env python3
# NOTICE: This file created by an LLM coding system on 2026-08-15.
"""Generate the deck outline and summary table in slides/index.html.

Everything between the generated-block markers in index.html is written by this
script, from the deck sources sitting next to it. The decks stay the single
place any of this wording is edited.

Each deck covers two class meetings, so the outline nests three levels deep:

    Week N deck
      Day M · Station — the day's title slide
        the day's `{.section-header}` topics

Days are found by their subtitle line rather than by heading text: every day
opens with one or more `{.title-slide}` headings followed by a line reading
`CS 377, Week N, Day M 🟦 Station 🟦`. A day that repeats its title as a
`.photo-title` variant is listed once, under the first of the pair, and the
station name is taken from whichever of them carries it.

Topics are the `{.section-header}` headings, which are already each deck's
table of contents. One can opt out with `{.section-header .no-index}`.

Anchors are derived from the source rather than read back out of the built
HTML, so the outline regenerates even when the decks have not been rendered.
slugify() reimplements pandoc's auto_identifiers, and *every* heading is walked
(not just the ones that get listed) because pandoc's duplicate suffixes count
all of them: week 3's two `# Introduction to Care Ethics` headings become
`introduction-to-care-ethics` and `introduction-to-care-ethics-1`.

The link form is `weekN.html#/slug`. reveal.js writes that shape into the URL
bar itself and reads it back with a regex that makes the slash optional, so it
matches what a user sees after navigating.

Slide counts in the summary table are the one thing read from the built HTML,
because the source cannot predict them: with `slide-level: 2` a `---` rule
inside a section opens a slide of its own, on top of one per heading. build.sh
runs this script after rendering, so the counts are current; a deck that has
not been built yet simply reports no count.

Usage:
  python3 sync_slide_index.py [slides-dir]
"""
import csv
import os
import re
import sys

# The course schedule, one row per class meeting. Read for the stops a week is
# supposed to have (so a cancelled class still gets one) and for the one-line
# topic summary in the table.
SCHEDULE_CSV = os.path.join('..', '_data', 'schedule.csv')
SCHEDULE_TOPICS = os.path.join('..', '_includes', 'schedule-topics.md')

LIST_BEGIN = '<!-- begin deck outline generated by sync_slide_index.py -->'
LIST_END = '<!-- end deck outline generated by sync_slide_index.py -->'
SUMMARY_BEGIN = '<!-- begin deck summary generated by sync_slide_index.py -->'
SUMMARY_END = '<!-- end deck summary generated by sync_slide_index.py -->'
PLACEHOLDER = 'Topic details in progress'

HEADING_RE = re.compile(r'^(#{1,6})\s+(.*?)\s*$')
# A trailing pandoc attribute block: {#explicit-id .class key="value"}
ATTR_RE = re.compile(r'\{([^{}]*)\}\s*$')
FENCE_RE = re.compile(r'^\s*(```+|~~~+)')
# The subtitle under every day's title slide.
DAY_RE = re.compile(r'^CS 377,\s*Week\s*(\d+),\s*Day\s*(\d+)')
STATION_RE = re.compile(r'🟦\s*(.+?)\s*🟦')
SECTION_RE = re.compile(r'<section\b[^>]*class="[^"]*\bslide\b')


# --------------------------------------------------------------------------
# Reading a deck source
# --------------------------------------------------------------------------

def deck_source(slides_dir, week):
    """(path, text) for a week's deck, or None. Decks are .md or .qmd."""
    for ext in ('md', 'qmd'):
        path = os.path.join(slides_dir, f'week{week}.{ext}')
        if os.path.exists(path):
            return path, open(path, encoding='utf-8').read()
    return None


def headings(lines):
    """Every ATX heading in order, as (level, text, attrs, line_no).

    Code fences are skipped: a `# comment` inside one would otherwise read as a
    heading. Front matter is skipped for the same reason, though these decks
    carry none of their own (settings live in _metadata.yml).
    """
    found = []
    i = 0
    if lines and lines[0].strip() == '---':
        for i in range(1, len(lines)):
            if lines[i].strip() in ('---', '...'):
                i += 1
                break
        else:
            i = len(lines)
    fence = None
    while i < len(lines):
        line = lines[i]
        opener = FENCE_RE.match(line)
        if fence is not None:
            # Only a fence of the same kind and at least the same length closes.
            if opener and opener.group(1)[0] == fence[0] and len(opener.group(1)) >= len(fence):
                fence = None
            i += 1
            continue
        if opener:
            fence = opener.group(1)
            i += 1
            continue
        m = HEADING_RE.match(line)
        if m:
            text = m.group(2)
            attrs = ''
            attr = ATTR_RE.search(text)
            if attr:
                attrs = attr.group(1)
                text = text[:attr.start()].strip()
            found.append((len(m.group(1)), text, attrs, i))
        i += 1
    return found


def strip_markup(text):
    """Heading text as pandoc sees it: inline formatting removed, not escaped."""
    text = re.sub(r'!?\[([^\]]*)\]\([^)]*\)', r'\1', text)   # links / images
    text = re.sub(r'<[^>]+>', '', text)                       # raw HTML
    text = re.sub(r'`([^`]*)`', r'\1', text)                  # code
    text = re.sub(r'(\*\*|__|\*|_)', '', text)                # emphasis
    return text.strip()


def slugify(text):
    """pandoc's auto_identifiers: what becomes the <section> id."""
    text = strip_markup(text)
    # Drop punctuation except underscores, hyphens and periods; spaces to dashes.
    text = ''.join(c for c in text if c.isalnum() or c in ' \t_-.')
    text = re.sub(r'[ \t]+', '-', text).lower()
    # Identifiers must start with a letter.
    text = re.sub(r'^[^a-z]+', '', text)
    return text or 'section'


def has_class(attrs, name):
    return re.search(r'(?:^|\s)\.' + re.escape(name) + r'(?:\s|$)', attrs) is not None


def subtitle_of(lines, line_no):
    """The first line of prose under a heading, skipping blanks and comments."""
    for line in lines[line_no + 1:]:
        stripped = line.strip()
        if not stripped or stripped.startswith('<!--'):
            continue
        if stripped == '---' or HEADING_RE.match(stripped):
            return ''
        return stripped
    return ''


# --------------------------------------------------------------------------
# Turning a deck into an outline
# --------------------------------------------------------------------------

def outline(source_text):
    """[{day, station, title, anchor, topics}] for one deck, in slide order.

    Section headers attach to the day that precedes them; any that appear
    before the first day title (there are none today) would be dropped, so
    they are collected into a leading dayless group instead.
    """
    lines = source_text.split('\n')
    days, seen = [], {}
    current = None
    for _level, raw, attrs, line_no in headings(lines):
        explicit = re.search(r'#([^\s}]+)', attrs)
        slug = explicit.group(1) if explicit else slugify(raw)
        # Pandoc disambiguates repeats with -1, -2, ... in document order.
        n = seen.get(slug, 0)
        seen[slug] = n + 1
        anchor = slug if n == 0 else f'{slug}-{n}'

        if has_class(attrs, 'title-slide'):
            subtitle = subtitle_of(lines, line_no)
            day_match = DAY_RE.match(subtitle)
            if day_match:
                station = STATION_RE.search(subtitle)
                number = int(day_match.group(2))
                if current is not None and current['day'] == number:
                    # The `.photo-title` twin of a day already listed: keep the
                    # first anchor, but let either slide supply the station.
                    if station and not current['station']:
                        current['station'] = station.group(1)
                    continue
                current = {
                    'day': number,
                    'station': station.group(1) if station else '',
                    'title': strip_markup(raw),
                    'anchor': anchor,
                    'topics': [],
                }
                days.append(current)
                continue

        if has_class(attrs, 'section-header') and not has_class(attrs, 'no-index'):
            if current is None:
                current = {'day': None, 'station': '', 'title': '',
                           'anchor': '', 'topics': []}
                days.append(current)
            current['topics'].append((strip_markup(raw), anchor))
    return days


# --------------------------------------------------------------------------
# Reading the course schedule
# --------------------------------------------------------------------------

def schedule_days(slides_dir):
    """{week: [(day, station, topic)]} — every class meeting, in date order.

    The CSV has no Day column: a week's meetings are numbered by their position
    within the week, which is the same numbering schedule-topics.md uses.
    """
    path = os.path.normpath(os.path.join(slides_dir, SCHEDULE_CSV))
    if not os.path.exists(path):
        return {}
    by_week = {}
    with open(path, encoding='utf-8', newline='') as fh:
        for row in csv.DictReader(fh):
            week = (row.get('Week') or '').strip()
            if not week.isdigit():
                continue
            meetings = by_week.setdefault(int(week), [])
            meetings.append((
                len(meetings) + 1,
                (row.get('Station') or '').strip(),
                (row.get('Topic') or '').strip(),
            ))
    return by_week


def schedule_notes(slides_dir):
    """{(week, day): "what happens"} — the top-level bullets of each day.

    Only used for days the decks say nothing about, to explain why: the
    holidays are written up in schedule-topics.md and nowhere else.
    """
    path = os.path.normpath(os.path.join(slides_dir, SCHEDULE_TOPICS))
    if not os.path.exists(path):
        return {}
    notes, key, in_sources = {}, None, False
    for line in open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        head = re.match(r'^## Week (\d+), Day (\d+)', line)
        if head:
            key = (int(head.group(1)), int(head.group(2)))
            in_sources = False
            continue
        if line.startswith('###'):
            in_sources = True
            continue
        item = re.match(r'^\* (.+)$', line)
        if key and not in_sources and item:
            notes.setdefault(key, []).append(strip_markup(item.group(1)))
    return {k: '; '.join(v) for k, v in notes.items()}


def week_topic(slides_dir, week, _cache={}):
    """The week's one-line topic summary, both meetings collapsed into one."""
    if 'days' not in _cache:
        _cache['days'] = schedule_days(slides_dir)
    seen = []
    for _day, _station, topic in _cache['days'].get(week, []):
        if topic and topic not in seen:
            seen.append(topic)
    return '; '.join(seen)


def slide_count(slides_dir, week):
    """Slides in the built deck, or None when it has not been rendered."""
    path = os.path.join(slides_dir, f'week{week}.html')
    if not os.path.exists(path):
        return None
    return len(SECTION_RE.findall(open(path, encoding='utf-8').read()))


def escape(text):
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


# --------------------------------------------------------------------------
# Rendering the outline
# --------------------------------------------------------------------------

def merge_schedule(days, meetings, notes, week):
    """Fold the week's scheduled meetings into the days the deck defines.

    A meeting the deck has no title slide for still earns a stop, so the line
    keeps one circle per class day: either the class was cancelled, and the
    schedule says why, or its slides are simply not written yet.
    """
    if not meetings:
        return days
    by_number = {d['day']: d for d in days if d['day']}
    merged = [d for d in days if not d['day']]
    for number, station, topic in meetings:
        if number in by_number:
            day = by_number[number]
            if not day['station']:
                day['station'] = station
            merged.append(day)
            continue
        note = notes.get((week, number), '')
        merged.append({
            'day': number,
            'station': station,
            'title': note or topic or 'Slides to come',
            'anchor': '',
            'topics': [],
            'off': 'no class' in note.lower(),
        })
    return merged


def deck_block(week, days, indent='  '):
    """The <li> for one deck: a nested list of its days and their topics."""
    pad = indent + '  '
    # No station list up here: every stop names itself on its own line below.
    out = [
        f'{indent}<li>',
        f'{pad}<a href="week{week}.html">Week {week} Slide Deck</a>',
        f'{pad}<ul>',
    ]
    for day in days:
        def topic_items(depth):
            return [
                f'{pad}{"  " * depth}<li>'
                f'<a href="week{week}.html#/{anchor}">{escape(topic)}</a></li>'
                for topic, anchor in day['topics']
            ]

        if not day['day']:
            # A deck with no dated class days (the week 0 starter deck): its
            # topics are the whole outline, so list them without a day above.
            out.extend(topic_items(1))
            continue

        # The station is a plaque, the same `🟦 Name 🟦` code span the schedule
        # page uses, so a stop is recognisable at a glance in either place.
        label = f'Day {day["day"]}'
        if day['station']:
            label += f' <code>🟦 {escape(day["station"])} 🟦</code>'
        title = escape(day['title'])
        text = f'{label} — {title}' if title else label
        if day['anchor']:
            body = f'<a href="week{week}.html#/{day["anchor"]}">{text}</a>'
            css = 'deck-day'
        elif day.get('off'):
            # A cancelled class: the schedule note already says why.
            body = text
            css = 'deck-day deck-day-off'
        else:
            # A real class the deck has no slides for yet.
            body = f'{text} <span class="deck-hint">slides to come</span>'
            css = 'deck-day deck-day-todo'
        out.append(f'{pad}  <li class="{css}">{body}')
        if day['topics']:
            out.append(f'{pad}    <ul>')
            out.extend(topic_items(3))
            out.append(f'{pad}    </ul>')
        out.append(f'{pad}  </li>')
    out.append(f'{pad}  <li class="deck-more">More:')
    out.append(f'{pad}    <ul>')
    out.append(f'{pad}      <li><a href="week{week}.pdf">PDF version of slides</a></li>')
    out.append(f'{pad}    </ul>')
    out.append(f'{pad}  </li>')
    out.append(f'{pad}</ul>')
    out.append(f'{indent}</li>')
    return out


def outline_block(slides_dir, weeks):
    meetings_by_week = schedule_days(slides_dir)
    notes = schedule_notes(slides_dir)
    lines = [LIST_BEGIN, '<ul class="sources">']
    for week in weeks:
        found = deck_source(slides_dir, week)
        if not found:
            continue
        days = merge_schedule(
            outline(found[1]), meetings_by_week.get(week, []), notes, week)
        if not days:
            lines.extend([
                '  <li>',
                f'    <a href="week{week}.html">Week {week} Slide Deck</a>'
                f' — {PLACEHOLDER}',
                '  </li>',
            ])
            continue
        lines.extend(deck_block(week, days))
    lines.extend(['</ul>', LIST_END])
    return lines


def summary_block(slides_dir, weeks):
    """The whole summary table: one row per deck, its slide count and topic.

    The Topic cell is the schedule's own one-line summary of the week (the
    Topic column of _data/schedule.csv, both meetings collapsed into one),
    deliberately a coarser view than the section headers listed above it.
    """
    rows = []
    for week in weeks:
        found = deck_source(slides_dir, week)
        if not found:
            continue
        count = slide_count(slides_dir, week)
        rows.append(
            f'      <tr><td><a href="week{week}.html">Week {week}</a></td>'
            f'<td>{count if count is not None else ""}</td>'
            f'<td>{escape(week_topic(slides_dir, week))}</td></tr>'
        )
    return [
        SUMMARY_BEGIN,
        '<div class="deck-table-wrap">',
        '  <table class="deck-table">',
        '    <thead>',
        '      <tr><th>Deck</th><th>Slides</th><th>Topics</th></tr>',
        '    </thead>',
        '    <tbody>',
        *rows,
        '    </tbody>',
        '  </table>',
        '</div>',
        SUMMARY_END,
    ]


def replace_between(text, begin, end, block):
    """Swap everything between two markers for freshly generated lines."""
    start, stop = text.find(begin), text.find(end)
    if start == -1 or stop == -1:
        return text, False
    return text[:start] + '\n'.join(block) + text[stop + len(end):], True


def main(slides_dir):
    index = os.path.join(slides_dir, 'index.html')
    original = open(index, encoding='utf-8').read()

    # week0 is the starter deck kept for copying, not a real class week, so it
    # is left out of the listing even though its file stays in place.
    weeks = sorted(
        int(m.group(1))
        for f in os.listdir(slides_dir)
        for m in [re.fullmatch(r'week(\d+)\.(?:md|qmd)', f)]
        if m and int(m.group(1)) != 0
    )

    text = original
    text, listed = replace_between(
        text, LIST_BEGIN, LIST_END, outline_block(slides_dir, weeks))
    text, summarized = replace_between(
        text, SUMMARY_BEGIN, SUMMARY_END, summary_block(slides_dir, weeks))

    if text != original:
        open(index, 'w', encoding='utf-8').write(text)

    notes = []
    if not listed:
        notes.append('deck outline markers missing')
    if not summarized:
        notes.append('deck summary markers missing')
    note = ('; ' + '; '.join(notes)) if notes else ''
    print(f'[sync-index] {len(weeks)} decks: '
          f'{" ".join(f"w{w}" for w in weeks)}{note}', file=sys.stderr)


if __name__ == '__main__':
    default_dir = os.path.dirname(os.path.abspath(__file__))
    main(sys.argv[1] if len(sys.argv) > 1 else default_dir)
