#!/usr/bin/env python3
"""NOTICE: This file was generated by an LLM-based coding system. Review before promoting out of sandbox/.

Build the site's tab identity and preview card out of artwork the site already uses.

Two marks, both cut from existing files rather than drawn fresh:

  icons   The Blue Line where it runs through the Loop -- down the Milwaukee-Dearborn
          diagonal, east under Lake, then the hook south through Washington and Jackson
          before turning west toward Forest Park. That hook is the one stretch of the
          route nobody would mistake for another line, which is what an icon needs at
          16px. Cropped out of assets/blue-line-full-path-tweak-divided.svg; the station
          circles are dropped, because at icon sizes they read as grit rather than stops.

  og      One car -- the ETHICS half of the masthead train
          (assets/trains/blue-line-ethics-masthead-v4c.svg) -- riding the same blue rail it
          rides at the top of every page, and nothing else. The card is the site's own
          header, not a second piece of branding, and at preview-thumbnail size a single
          word on a line survives the shrink where a sentence would not.

Writes, relative to docs/:
    favicon.ico                          16/32/48/64/128 px, transparent
    assets/branding/loop-icon.svg        vector favicon for browsers that take one
    assets/branding/apple-touch-icon.png 180px, on white (iOS ignores alpha)
    assets/branding/icon-192.png, icon-512.png   Android/PWA, named in site.webmanifest
    assets/branding/blue-line-og.png     1200x630 preview card
"""

import argparse
import io
import re
from pathlib import Path

import cairosvg
from PIL import Image, ImageDraw

HERE = Path(__file__).resolve().parent
DOCS = HERE.parents[2]

MAP_SRC = "assets/blue-line-full-path-tweak-divided.svg"
TRAIN_SRC = "assets/trains/blue-line-ethics-masthead-v4c.svg"

BLUE = "#00A1DE"          # CTA Blue Line, the same value css/index.css uses

# The Loop hook in map units. The track centerline there runs x 750..850, y 798..975; the
# box is that plus half of ICON_STROKE on every side, squared up, so the diagonal enters the
# top edge and the Forest Park branch leaves the left one.
LOOP_BOX = (733, 781, 134, 211)   # x, y, w, h
# The map draws the route at stroke 26. Scaled down to 16px that lands under two pixels and
# the hook washes out, so the icon is drawn heavier -- the shape stays the same, the line
# just holds its color at tab size.
ICON_STROKE = 34
ICO_SIZES = (16, 32, 48, 64, 128)
PWA_SIZES = (192, 512)

OG_SIZE = (1200, 630)
OG_RAIL_H = 14
OG_RAIL_OVERLAP = 3     # how far the wheels sink into the bar
OG_TRAIN_W = 880
# The masthead is two cars, BLUE LINE and ETHICS, on one 2440x400 canvas with a gap between
# them; the second car's ink starts at x=1246 and ends at x=2401. Re-framing the viewBox on
# that span takes the ETHICS car alone without touching the drawing, and keeping the full
# 0..400 height means the wheel geometry below still holds.
OG_CAR_X, OG_CAR_W = 1246, 1156
OG_CAR_H = 400


def loop_svg(docs: Path, pad: float = 14.0) -> str:
    """The route path alone, re-framed on the Loop hook and squared up."""
    text = (docs / MAP_SRC).read_text()
    d = re.search(r'<path id="path1"[^>]*\bd="([^"]+)"', text).group(1)
    x, y, w, h = LOOP_BOX
    side = max(w, h) + 2 * pad       # square viewBox so the icon never distorts
    x -= (side - w) / 2
    y -= (side - h) / 2
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{side:.0f}" height="{side:.0f}" '
        f'viewBox="{x:.2f} {y:.2f} {side:.2f} {side:.2f}">'
        f'<path fill="none" stroke="{BLUE}" stroke-width="{ICON_STROKE}" d="{d}"/>'
        f'</svg>'
    )


def render(markup: str, width: int, height: int | None = None,
           bg: str | None = None) -> Image.Image:
    png = cairosvg.svg2png(bytestring=markup.encode("utf-8"),
                           output_width=width, output_height=height or width,
                           background_color=bg)
    return Image.open(io.BytesIO(png)).convert("RGBA")


def build_icons(docs: Path, pad: float) -> list[Path]:
    markup = loop_svg(docs, pad)
    assets = docs / "assets" / "branding"
    written = []

    svg_path = assets / "loop-icon.svg"
    svg_path.write_text(markup + "\n")
    written.append(svg_path)

    # Every size is rendered from the vector rather than resampled off one bitmap.
    layers = [render(markup, s) for s in ICO_SIZES]
    ico_path = docs / "favicon.ico"
    layers[-1].save(ico_path, format="ICO", sizes=[(s, s) for s in ICO_SIZES],
                    append_images=layers)
    written.append(ico_path)

    touch = assets / "apple-touch-icon.png"
    render(markup, 180, bg="#ffffff").convert("RGB").save(touch, optimize=True)
    written.append(touch)

    # On white, since Android composites home-screen icons on its own plate and a
    # transparent one can disappear against a dark wallpaper.
    for size in PWA_SIZES:
        p = assets / f"icon-{size}.png"
        render(markup, size, bg="#ffffff").convert("RGB").save(p, optimize=True)
        written.append(p)

    return written


def car_svg(docs: Path) -> str:
    """The masthead's ETHICS car alone, re-framed out of the two-car artwork."""
    text = (docs / TRAIN_SRC).read_text()
    body = re.search(r"<svg\b[^>]*>(.*)</svg>", text, re.DOTALL).group(1)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{OG_CAR_W}" height="{OG_CAR_H}" '
        f'viewBox="{OG_CAR_X} 0 {OG_CAR_W} {OG_CAR_H}">{body}</svg>'
    )


def build_og(docs: Path) -> Path:
    w, h = OG_SIZE
    card = Image.new("RGB", (w, h), "#ffffff")

    train = render(car_svg(docs), OG_TRAIN_W, round(OG_TRAIN_W * OG_CAR_H / OG_CAR_W))
    # Measure the drawing rather than trusting the canvas: the masthead's 2440x400 frame has
    # slack above the roof and below the wheels, so centering the image would not center the
    # car. Everything below is keyed to the ink itself.
    # Thresholded, not a plain getbbox(): the artwork carries a few near-transparent
    # pixels below the wheels, and counting those as ink floats the car off the rail.
    solid = train.split()[3].point(lambda a: 255 if a > 24 else 0)
    x0, y0, x1, y1 = solid.getbbox()

    paste_x = round((w - (x1 - x0)) / 2) - x0
    paste_y = round((h - (y1 - y0)) / 2) - y0
    card.paste(train, (paste_x, paste_y), train)

    # The rail's top edge lands just inside the bottom of the wheels, so the car rests on the
    # line the way the masthead train rests on its bar.
    rail_y = paste_y + y1 - OG_RAIL_OVERLAP
    ImageDraw.Draw(card).rectangle([0, rail_y, w, rail_y + OG_RAIL_H], fill=BLUE)

    out = docs / "assets" / "branding" / "blue-line-og.png"
    card.save(out, optimize=True)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--docs", type=Path, default=DOCS, help="site root to write into")
    ap.add_argument("--pad", type=float, default=14.0, help="margin around the hook, map units")
    args = ap.parse_args()

    written = build_icons(args.docs, args.pad)
    written.append(build_og(args.docs))

    for p in written:
        print(f"wrote {p.relative_to(args.docs)} ({p.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
